from typing import Protocol, Optional, List, Any
from uuid import UUID

from src.domain.entities import Candidate, CandidateDocument, AIExtraction, AuditLog, BackgroundJob, ResumeIngestionRequest

class CandidateRepository(Protocol):
    async def create(self, candidate: Candidate) -> Candidate: ...
    async def get_by_id(self, id: UUID) -> Optional[Candidate]: ...
    async def get_all(self, skip: int = 0, limit: int = 100) -> List[Candidate]: ...
    async def update(self, candidate: Candidate) -> Candidate: ...
    async def delete(self, id: UUID) -> bool: ...

class CandidateDocumentRepository(Protocol):
    async def create(self, document: CandidateDocument) -> CandidateDocument: ...
    async def get_by_id(self, id: UUID) -> Optional[CandidateDocument]: ...
    async def get_by_candidate_id(self, candidate_id: UUID) -> List[CandidateDocument]: ...

class AIExtractionRepository(Protocol):
    async def create(self, extraction: AIExtraction) -> AIExtraction: ...
    async def get_by_document_id(self, document_id: UUID) -> List[AIExtraction]: ...

class AuditRepository(Protocol):
    async def log_action(self, entity_type: str, entity_id: UUID, action: str, changes: dict[str, Any]) -> AuditLog: ...
    async def get_by_entity(self, entity_type: str, entity_id: UUID) -> List[AuditLog]: ...

class JobRepository(Protocol):
    async def create(self, job: BackgroundJob) -> BackgroundJob: ...
    async def get_by_id(self, id: UUID) -> Optional[BackgroundJob]: ...
    async def update(self, job: BackgroundJob) -> BackgroundJob: ...

class ResumeIngestionRequestRepository(Protocol):
    async def create(self, request: ResumeIngestionRequest) -> ResumeIngestionRequest: ...
    async def get_by_id(self, id: UUID) -> Optional[ResumeIngestionRequest]: ...
    async def get_by_document_id(self, document_id: UUID) -> Optional[ResumeIngestionRequest]: ...
    async def update(self, request: ResumeIngestionRequest) -> ResumeIngestionRequest: ...
