from typing import Protocol, List, Optional
from uuid import UUID
from src.domain.coordination_models import (
    AgentMessage, Goal, GoalNode, DelegationPlan, 
    CoordinationSession, Consensus, Conflict
)

class AgentCommunicationBus(Protocol):
    async def send(self, message: AgentMessage) -> None: ...
    async def publish(self, topic: str, message: AgentMessage) -> None: ...
    async def broadcast(self, message: AgentMessage) -> None: ...
    async def reply(self, original_id: UUID, message: AgentMessage) -> None: ...
    async def subscribe(self, topic: str, handler: callable) -> None: ...

class AgentMailbox(Protocol):
    async def enqueue(self, message: AgentMessage) -> None: ...
    async def dequeue(self) -> Optional[AgentMessage]: ...
    async def peek(self) -> Optional[AgentMessage]: ...
    async def archive(self, message_id: UUID) -> None: ...
    async def get_messages(self) -> List[AgentMessage]: ...

class GoalEngine(Protocol):
    async def decompose(self, goal: Goal) -> List[GoalNode]: ...
    async def get_dependencies(self, node_id: UUID) -> List[UUID]: ...

class DelegationPlanner(Protocol):
    async def create_plan(self, nodes: List[GoalNode]) -> DelegationPlan: ...

class DelegationEngine(Protocol):
    async def assign_plan(self, plan: DelegationPlan) -> None: ...

class CoordinationStrategy(Protocol):
    async def execute(self, plan: DelegationPlan) -> None: ...

class ConsensusEngine(Protocol):
    async def evaluate(self, goal_id: UUID) -> Consensus: ...

class ConflictResolver(Protocol):
    async def resolve(self, conflict: Conflict) -> str: ...

class Supervisor(Protocol):
    async def receive_goal(self, goal: Goal) -> None: ...
    async def trigger_consensus(self, goal_id: UUID) -> None: ...

class CoordinationRuntime(Protocol):
    async def start(self) -> CoordinationSession: ...
    async def pause(self) -> None: ...
    async def resume(self) -> None: ...
    async def cancel(self) -> None: ...
    async def status(self) -> str: ...
