from typing import Protocol, List, Optional
from uuid import UUID
from src.domain.organization_models import AgentSkill, OrganizationGoal, OrganizationPolicy

class SkillRegistry(Protocol):
    async def register(self, skill: AgentSkill) -> None: ...
    async def discover(self) -> List[AgentSkill]: ...
    async def search(self, query: str) -> List[AgentSkill]: ...
    async def execute(self, skill_id: UUID, payload: dict) -> dict: ...
    async def version(self, skill_id: UUID) -> str: ...

class OrganizationPolicyEngine(Protocol):
    async def validate(self, policy: OrganizationPolicy, execution_context: dict) -> bool: ...

class LearningLoop(Protocol):
    async def trigger(self, goal_id: UUID) -> None: ...

class OrganizationFacade(Protocol):
    async def bootstrap(self) -> None: ...
    async def ingest_goal(self, goal: OrganizationGoal) -> None: ...
