from typing import Protocol, List, Optional, Dict, Any
from uuid import UUID
from pydantic import BaseModel
from src.domain.tool_models import ToolMetadata, ToolExecutionResult, ExecutionBudget

class ToolExecutionContext(BaseModel):
    request_id: UUID
    workflow_id: UUID
    execution_id: UUID
    memory_context: Optional[Dict[str, Any]] = None
    user_context: Optional[Dict[str, Any]] = None
    system_context: Optional[Dict[str, Any]] = None
    permissions: List[str] = []
    configuration: Dict[str, Any] = {}
    trace_context: Dict[str, Any] = {}
    budget: Optional[ExecutionBudget] = None

class ContextBuilder(Protocol):
    async def build(self, workflow_id: UUID, overrides: Dict[str, Any] = None) -> ToolExecutionContext:
        ...

class ToolProvider(Protocol):
    @property
    def provider_id(self) -> str: ...
    async def connect(self) -> None: ...
    async def discover_tools(self) -> List[ToolMetadata]: ...
    async def execute(self, tool_id: str, arguments: Dict[str, Any], context: ToolExecutionContext) -> ToolExecutionResult: ...
    async def health(self) -> str: ...
    async def disconnect(self) -> None: ...

class ProviderManager(Protocol):
    async def register_provider(self, provider: ToolProvider) -> None: ...
    async def get_provider(self, provider_id: str) -> ToolProvider: ...
    async def monitor_health(self) -> None: ...

class ToolRegistry(Protocol):
    async def register(self, metadata: ToolMetadata) -> None: ...
    async def unregister(self, tool_id: str) -> None: ...
    async def discover(self) -> List[ToolMetadata]: ...
    async def search(self, query: str) -> List[ToolMetadata]: ...
    async def get(self, tool_id: str) -> ToolMetadata: ...
    async def list(self) -> List[ToolMetadata]: ...

class CapabilityResolver(Protocol):
    async def resolve(self, capability: str, operation: str) -> ToolMetadata: ...

class PermissionStore(Protocol):
    async def get_allowed_capabilities(self, context: ToolExecutionContext) -> List[str]: ...

class ToolPolicy(Protocol):
    async def evaluate(self, tool: ToolMetadata, context: ToolExecutionContext) -> bool: ...

class ToolExecutor(Protocol):
    async def execute(self, capability: str, operation: str, arguments: Dict[str, Any], context: ToolExecutionContext) -> ToolExecutionResult: ...
    async def retry(self, execution_id: UUID) -> ToolExecutionResult: ...
    async def timeout(self, execution_id: UUID) -> None: ...
    async def cancel(self, execution_id: UUID) -> None: ...

class ToolPipeline(Protocol):
    """Stub for chained tool execution."""
    async def execute_chain(self, steps: List[Dict[str, Any]], context: ToolExecutionContext) -> ToolExecutionResult: ...

class ToolCache(Protocol):
    async def cache(self, key: str, result: ToolExecutionResult, ttl: int) -> None: ...
    async def retrieve(self, key: str) -> Optional[ToolExecutionResult]: ...
    async def invalidate(self, key: str) -> None: ...
