from enum import Enum

class CandidateStatus(str, Enum):
    NEW = "NEW"
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    TEXT_EXTRACTED = "TEXT_EXTRACTED"
    AI_EXTRACTION_RUNNING = "AI_EXTRACTION_RUNNING"
    PROFILE_GENERATED = "PROFILE_GENERATED"
    UNDER_REVIEW = "UNDER_REVIEW"
    SHORTLISTED = "SHORTLISTED"
    INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED"
    REJECTED = "REJECTED"
    HIRED = "HIRED"

class WorkflowStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"

class InterruptReason(str, Enum):
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    MISSING_REQUIRED_DATA = "MISSING_REQUIRED_DATA"

class MemoryNamespace(str, Enum):
    RECRUITER = "RECRUITER"
    CANDIDATE = "CANDIDATE"
    WORKFLOW = "WORKFLOW"
    ORGANIZATION = "ORGANIZATION"
    SYSTEM = "SYSTEM"

class MemoryRetentionPolicy(str, Enum):
    PERMANENT = "PERMANENT"
    EXPIRING = "EXPIRING"
    SESSION = "SESSION"
    CONSOLIDATED = "CONSOLIDATED"

class JobStatus(str, Enum):
    PENDING = "PENDING"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    RETRYING = "RETRYING"

class EmbeddingType(str, Enum):
    FULL_PROFILE = "FULL_PROFILE"
    SKILLS = "SKILLS"
    EXPERIENCE = "EXPERIENCE"
    EDUCATION = "EDUCATION"
    PROJECTS = "PROJECTS"
    SUMMARY = "SUMMARY"

class JobRequirementStatus(str, Enum):
    DRAFT = "DRAFT"
    OPEN = "OPEN"
    CLOSED = "CLOSED"

class RecruiterDecision(str, Enum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    SHORTLISTED = "SHORTLISTED"
    INTERVIEW = "INTERVIEW"
    MAYBE = "MAYBE"

class GroundTruthEventType(str, Enum):
    APPLIED = "APPLIED"
    INTERVIEWED = "INTERVIEWED"
    OFFERED = "OFFERED"
    ACCEPTED = "ACCEPTED"
    HIRED = "HIRED"
    REJECTED = "REJECTED"
    WITHDRAWN = "WITHDRAWN"
