import { BookOpen } from "lucide-react";
import { useOrganizationLearning } from "@/hooks/useOrganization";
import { OrganizationWidgetWrapper } from "./OrganizationWidgetWrapper";

export function OrganizationLearningWidget() {
  const { data, isLoading, isError } = useOrganizationLearning();

  return (
    <OrganizationWidgetWrapper
      title="Learning"
      description="Insights and knowledge generated by the organization."
      icon={<BookOpen className="w-5 h-5 text-muted-foreground" />}
      isLoading={isLoading}
      isError={isError}
      data={data}
    >
      {(learning) => <pre>{JSON.stringify(learning, null, 2)}</pre>}
    </OrganizationWidgetWrapper>
  );
}
