from typing import Protocol, List, Dict, Any, Optional
from uuid import UUID
from src.domain.agent_models import (
    Agent, AgentTemplate, AgentSession, ReasoningTrace, 
    AgentContext, AgentObservation, AgentThought, AgentAction, AgentReflection, AgentPlan
)

class AgentRegistry(Protocol):
    async def register(self, agent: Agent) -> None: ...
    async def get(self, agent_id: UUID) -> Optional[Agent]: ...
    async def list(self) -> List[Agent]: ...

class AgentTemplateRegistry(Protocol):
    async def register(self, template: AgentTemplate) -> None: ...
    async def get(self, template_id: UUID) -> Optional[AgentTemplate]: ...

class AgentRuntime(Protocol):
    async def create(self, template_id: UUID) -> Agent: ...
    async def start(self, agent_id: UUID, context: AgentContext) -> AgentSession: ...
    async def pause(self, agent_id: UUID) -> None: ...
    async def resume(self, agent_id: UUID) -> None: ...
    async def cancel(self, agent_id: UUID) -> None: ...
    async def terminate(self, agent_id: UUID) -> None: ...
    async def heartbeat(self, agent_id: UUID) -> None: ...
    async def status(self, agent_id: UUID) -> str: ...

class RuntimeScheduler(Protocol):
    async def queue_execution(self, agent_id: UUID, context: AgentContext) -> None: ...
    async def prioritize(self, agent_id: UUID, priority: int) -> None: ...

class CognitivePipeline(Protocol):
    """Orchestrates Observe -> Retrieve -> Reason -> Plan -> Execute -> Reflect -> Learn"""
    async def execute_iteration(self, session: AgentSession, context: AgentContext) -> ReasoningTrace: ...

class Planner(Protocol):
    async def plan(self, observation: AgentObservation, context: AgentContext) -> AgentPlan: ...

class ReflectionEngine(Protocol):
    async def reflect(self, trace: ReasoningTrace, context: AgentContext) -> AgentReflection: ...

class AgentExecutor(Protocol):
    """Interacts with ToolPlatform and MemoryPlatform directly"""
    async def execute_action(self, action: AgentAction, context: AgentContext) -> Dict[str, Any]: ...

class AgentPolicy(Protocol):
    async def validate_budget(self, session: AgentSession) -> bool: ...

class ReplayEngine(Protocol):
    """Facilitates DRY_RUN and REPLAY execution modes by mocking executor outputs using historic ReasoningTraces"""
    async def replay_session(self, session_id: UUID) -> List[ReasoningTrace]: ...
