"""add_checkpoints_and_memory

Revision ID: 0f797c1eaffc
Revises: 3928df9f7ec0
Create Date: 2026-06-28 13:40:20.909511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '0f797c1eaffc'
down_revision: Union[str, Sequence[str], None] = '3928df9f7ec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('checkpoint_ns', sa.String(length=255), nullable=False),
    sa.Column('checkpoint_id', sa.String(length=255), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx')
    )
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('checkpoint_ns', sa.String(length=255), nullable=False),
    sa.Column('checkpoint_id', sa.String(length=255), nullable=False),
    sa.Column('parent_checkpoint_id', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id')
    )
    op.create_table('memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('namespace', sa.String(length=50), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('decay_score', sa.Float(), nullable=False),
    sa.Column('retention_policy', sa.String(length=50), nullable=False),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_external_reference'), 'memories', ['external_reference'], unique=False)
    op.create_index(op.f('ix_memories_namespace'), 'memories', ['namespace'], unique=False)
    op.create_table('working_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('volatile_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_working_memory_expires_at'), 'working_memory', ['expires_at'], unique=False)
    op.create_index(op.f('ix_working_memory_session_id'), 'working_memory', ['session_id'], unique=True)
    op.create_table('memory_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('provenance', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['memories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['memories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_edges_relationship_type'), 'memory_edges', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_memory_edges_source_node_id'), 'memory_edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_memory_edges_target_node_id'), 'memory_edges', ['target_node_id'], unique=False)
    op.create_table('memory_vectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('memory_id', sa.UUID(), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('embedding_version', sa.String(length=50), nullable=False),
    sa.Column('content_hash', sa.String(length=255), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('vector_data', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memory_vectors_data', 'memory_vectors', ['vector_data'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'vector_data': 'vector_cosine_ops'})
    op.create_index(op.f('ix_memory_vectors_memory_id'), 'memory_vectors', ['memory_id'], unique=False)
    op.alter_column('candidate_embeddings', 'vector_data',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               nullable=True)
    op.alter_column('job_requirement_embeddings', 'vector_data',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_requirement_embeddings', 'vector_data',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               nullable=False)
    op.alter_column('candidate_embeddings', 'vector_data',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               nullable=False)
    op.drop_index(op.f('ix_memory_vectors_memory_id'), table_name='memory_vectors')
    op.drop_index('idx_memory_vectors_data', table_name='memory_vectors', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'vector_data': 'vector_cosine_ops'})
    op.drop_table('memory_vectors')
    op.drop_index(op.f('ix_memory_edges_target_node_id'), table_name='memory_edges')
    op.drop_index(op.f('ix_memory_edges_source_node_id'), table_name='memory_edges')
    op.drop_index(op.f('ix_memory_edges_relationship_type'), table_name='memory_edges')
    op.drop_table('memory_edges')
    op.drop_index(op.f('ix_working_memory_session_id'), table_name='working_memory')
    op.drop_index(op.f('ix_working_memory_expires_at'), table_name='working_memory')
    op.drop_table('working_memory')
    op.drop_index(op.f('ix_memories_namespace'), table_name='memories')
    op.drop_index(op.f('ix_memories_external_reference'), table_name='memories')
    op.drop_table('memories')
    op.drop_table('checkpoints')
    op.drop_table('checkpoint_writes')
    # ### end Alembic commands ###
