"""add job workspace fields

Revision ID: 3928df9f7ec0
Revises: 036a0e5a21eb
Create Date: 2026-06-27 12:31:43.292691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3928df9f7ec0'
down_revision: Union[str, Sequence[str], None] = '036a0e5a21eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_requirements', sa.Column('department', sa.String(length=255), nullable=True))
    op.add_column('job_requirements', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('job_requirements', sa.Column('employment_type', sa.String(length=100), nullable=True))
    op.add_column('job_requirements', sa.Column('hiring_manager', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_requirements', 'hiring_manager')
    op.drop_column('job_requirements', 'employment_type')
    op.drop_column('job_requirements', 'location')
    op.drop_column('job_requirements', 'department')
    # ### end Alembic commands ###
