"""Add ToolExecutionModel

Revision ID: 417194ced827
Revises: 8da038e03d2f
Create Date: 2026-06-28 18:05:15.871418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '417194ced827'
down_revision: Union[str, Sequence[str], None] = '8da038e03d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('coordination_session_id', sa.UUID(), nullable=True),
    sa.Column('execution_budget_id', sa.UUID(), nullable=True),
    sa.Column('trace_id', sa.String(length=255), nullable=True),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('tool', sa.String(length=255), nullable=False),
    sa.Column('operation', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_executions_agent_id'), 'tool_executions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_tool_executions_trace_id'), 'tool_executions', ['trace_id'], unique=False)
    op.create_index(op.f('ix_tool_executions_workflow_id'), 'tool_executions', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_executions_workflow_id'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_trace_id'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_agent_id'), table_name='tool_executions')
    op.drop_table('tool_executions')
    # ### end Alembic commands ###
