"""add_workflow_executions

Revision ID: 8da038e03d2f
Revises: 0f797c1eaffc
Create Date: 2026-06-28 14:39:08.918632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8da038e03d2f'
down_revision: Union[str, Sequence[str], None] = '0f797c1eaffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_name', sa.String(length=100), nullable=False),
    sa.Column('workflow_version', sa.String(length=50), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_node', sa.String(length=100), nullable=True),
    sa.Column('current_checkpoint_id', sa.String(length=255), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_executions_status'), 'workflow_executions', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_executions_thread_id'), 'workflow_executions', ['thread_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_workflow_name'), 'workflow_executions', ['workflow_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_executions_workflow_name'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_thread_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_status'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    # ### end Alembic commands ###
