"""Add Workflow Observability Models

Revision ID: b7d2463c44d1
Revises: 4533a9382b72
Create Date: 2026-08-16 04:51:18.665265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7d2463c44d1'
down_revision: Union[str, Sequence[str], None] = '4533a9382b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('langgraph_checkpoints',
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('checkpoint_id', sa.String(length=255), nullable=False),
    sa.Column('parent_checkpoint_id', sa.String(length=255), nullable=True),
    sa.Column('checkpoint_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_id')
    )
    op.create_table('workflow_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_execution_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=True),
    sa.Column('metadata_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_events_category'), 'workflow_events', ['category'], unique=False)
    op.create_index(op.f('ix_workflow_events_timestamp'), 'workflow_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_workflow_events_workflow_execution_id'), 'workflow_events', ['workflow_execution_id'], unique=False)
    op.create_table('workflow_node_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_execution_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('outputs', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('tool_invocations', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_node_executions_node_id'), 'workflow_node_executions', ['node_id'], unique=False)
    op.create_index(op.f('ix_workflow_node_executions_workflow_execution_id'), 'workflow_node_executions', ['workflow_execution_id'], unique=False)

    op.add_column('workflow_executions', sa.Column('job_id', sa.UUID(), nullable=True))
    op.add_column('workflow_executions', sa.Column('candidate_id', sa.UUID(), nullable=True))
    op.add_column('workflow_executions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('workflow_executions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('workflow_executions', 'workflow_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('workflow_executions', 'current_node',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('workflow_executions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_workflow_executions_thread_id'), table_name='workflow_executions')
    op.create_index(op.f('ix_workflow_executions_thread_id'), 'workflow_executions', ['thread_id'], unique=True)
    op.create_index(op.f('ix_workflow_executions_candidate_id'), 'workflow_executions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_job_id'), 'workflow_executions', ['job_id'], unique=False)
    op.drop_column('workflow_executions', 'current_checkpoint_id')
    op.drop_column('workflow_executions', 'retry_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_executions', sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('workflow_executions', sa.Column('current_checkpoint_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_workflow_executions_job_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_candidate_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_thread_id'), table_name='workflow_executions')
    op.create_index(op.f('ix_workflow_executions_thread_id'), 'workflow_executions', ['thread_id'], unique=False)
    op.alter_column('workflow_executions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflow_executions', 'current_node',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('workflow_executions', 'workflow_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('workflow_executions', 'updated_at')
    op.drop_column('workflow_executions', 'created_at')
    op.drop_column('workflow_executions', 'candidate_id')
    op.drop_column('workflow_executions', 'job_id')

    op.drop_index(op.f('ix_workflow_node_executions_workflow_execution_id'), table_name='workflow_node_executions')
    op.drop_index(op.f('ix_workflow_node_executions_node_id'), table_name='workflow_node_executions')
    op.drop_table('workflow_node_executions')
    op.drop_index(op.f('ix_workflow_events_workflow_execution_id'), table_name='workflow_events')
    op.drop_index(op.f('ix_workflow_events_timestamp'), table_name='workflow_events')
    op.drop_index(op.f('ix_workflow_events_category'), table_name='workflow_events')
    op.drop_table('workflow_events')
    op.drop_table('langgraph_checkpoints')
    # ### end Alembic commands ###
